### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by YoloNet** [Zain-ul-din/whatsapp-ai-bot#55]
installing dependencies
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/WhiskeySockets/libsignal-node.git
Directory: /root/WhatsApp-Ai-bot
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
npm ERR! code 128
npm ERR! path /root/WhatsApp-Ai-bot
npm ERR! command failed
npm ERR! command sh -c yarn

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-09-23T15_51_19_732Z-debug.log
✔ dependencies has been installed
initializing server
yarn run v1.22.22
$ vite-node ./src/index.ts
/bin/sh: 1: vite-node: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code 127
npm ERR! path /root/WhatsApp-Ai-bot
npm ERR! command failed
npm ERR! command sh -c yarn "dev"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-09-23T15_51_20_846Z-debug.log

**Comment by Zain-ul-din** [comment]
Hey @YoloNet thank you for reporting the issue. This error is coming from `WhiskeySockets/baileys` since they [have](https://github.com/WhiskeySockets/Baileys/blob/master/package.json#L54) `git` dependency in their `package.json` to resolve that you must have SSH setup. [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) is a tutorial on how to setup ssh and connect it with Github. let me know if issue persists.
